import type { Product, Category } from '../types';

const categories: Category[] = [
  { id: 'cat-1', name: 'Dresses', slug: 'dresses', description: 'Elegant dresses for every occasion', image_url: null, sort_order: 1 },
  { id: 'cat-2', name: 'Tops', slug: 'tops', description: 'Effortless everyday tops', image_url: null, sort_order: 2 },
  { id: 'cat-3', name: 'Bottoms', slug: 'bottoms', description: 'Refined bottoms & trousers', image_url: null, sort_order: 3 },
  { id: 'cat-4', name: 'Outerwear', slug: 'outerwear', description: 'Layer up in style', image_url: null, sort_order: 4 },
  { id: 'cat-5', name: 'Accessories', slug: 'accessories', description: 'Finishing touches', image_url: null, sort_order: 5 },
];

export const MOCK_PRODUCTS: Product[] = [
  // ── TOPS ──
  {
    id: 'p-1',
    name: 'Linen Wrap Blouse',
    slug: 'linen-wrap-blouse',
    description: 'A breathable linen blouse with a flattering wrap silhouette. Designed to drape beautifully and transition from day to evening effortlessly. The relaxed fit and natural texture make this a wardrobe essential.',
    price: 89,
    compare_price: null,
    category_id: 'cat-2',
    category: categories[1],
    images: ['https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Sage', hex: '#8a9c85' },
      { name: 'Sand', hex: '#c5b5a5' },
      { name: 'Noir', hex: '#2c2c2c' },
    ],
    stock_quantity: 24,
    is_featured: true,
    is_active: true,
    tags: ['new', 'linen', 'bestseller'],
    care_instructions: 'Hand wash cold, lay flat to dry',
    material: '100% European Linen',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p-2',
    name: 'Silk Camisole',
    slug: 'silk-camisole',
    description: 'A luxuriously soft silk camisole with delicate spaghetti straps. Perfect for layering under blazers or wearing on its own for an elevated minimal look.',
    price: 68,
    compare_price: null,
    category_id: 'cat-2',
    category: categories[1],
    images: ['https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Cream', hex: '#f5efe6' },
      { name: 'Blush', hex: '#d4a5a5' },
      { name: 'Champagne', hex: '#c9a84c' },
    ],
    stock_quantity: 18,
    is_featured: false,
    is_active: true,
    tags: ['silk', 'layering'],
    care_instructions: 'Dry clean recommended',
    material: '100% Mulberry Silk',
    created_at: '2026-01-28T00:00:00Z',
  },
  {
    id: 'p-3',
    name: 'Oversized Cotton Tee',
    slug: 'oversized-cotton-tee',
    description: 'Premium organic cotton in a relaxed oversized cut. The perfect foundation piece — soft, breathable, and endlessly versatile.',
    price: 52,
    compare_price: null,
    category_id: 'cat-2',
    category: categories[1],
    images: ['https://images.unsplash.com/photo-1521577352947-9bb58764b69a?w=600&h=800&fit=crop'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Oat', hex: '#d4c9bc' },
      { name: 'Sage', hex: '#8a9c85' },
    ],
    stock_quantity: 40,
    is_featured: false,
    is_active: true,
    tags: ['cotton', 'basics', 'organic'],
    care_instructions: 'Machine wash cold, tumble dry low',
    material: '100% Organic Cotton',
    created_at: '2026-01-20T00:00:00Z',
  },

  // ── DRESSES ──
  {
    id: 'p-4',
    name: 'Midi Slip Dress',
    slug: 'midi-slip-dress',
    description: 'A timeless midi slip dress in fluid satin. The bias cut follows your natural silhouette while the adjustable straps ensure the perfect fit. Dress it up with heels or down with flats.',
    price: 98,
    compare_price: 145,
    category_id: 'cat-1',
    category: categories[0],
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Gold', hex: '#c9a84c' },
      { name: 'Ivory', hex: '#f5efe6' },
    ],
    stock_quantity: 12,
    is_featured: true,
    is_active: true,
    tags: ['sale', 'satin', 'bestseller'],
    care_instructions: 'Dry clean only',
    material: 'Satin-finish Viscose',
    created_at: '2026-02-05T00:00:00Z',
  },
  {
    id: 'p-5',
    name: 'Linen Maxi Dress',
    slug: 'linen-maxi-dress',
    description: 'A flowing linen maxi dress with a smocked bodice and tiered skirt. Effortlessly romantic, this piece captures the spirit of a Mediterranean summer.',
    price: 135,
    compare_price: null,
    category_id: 'cat-1',
    category: categories[0],
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Olive', hex: '#6a7c65' },
      { name: 'Cream', hex: '#f5efe6' },
    ],
    stock_quantity: 15,
    is_featured: true,
    is_active: true,
    tags: ['new', 'linen', 'maxi'],
    care_instructions: 'Machine wash cold, line dry',
    material: '100% French Linen',
    created_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'p-6',
    name: 'Knit Wrap Dress',
    slug: 'knit-wrap-dress',
    description: 'A figure-flattering wrap dress in soft ribbed knit. The perfect desk-to-dinner piece with a self-tie waist and gentle stretch for all-day comfort.',
    price: 110,
    compare_price: null,
    category_id: 'cat-1',
    category: categories[0],
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=800&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Sage', hex: '#7a8c75' },
      { name: 'Noir', hex: '#2c2c2c' },
      { name: 'Taupe', hex: '#b5a090' },
    ],
    stock_quantity: 20,
    is_featured: false,
    is_active: true,
    tags: ['knit', 'wrap'],
    care_instructions: 'Hand wash cold, reshape and dry flat',
    material: 'Cotton-Viscose Blend',
    created_at: '2026-01-15T00:00:00Z',
  },

  // ── OUTERWEAR ──
  {
    id: 'p-7',
    name: 'Botanical Jacket',
    slug: 'botanical-jacket',
    description: 'A structured linen-blend jacket with a relaxed fit and artisanal botanical embroidery detail. Lined in cotton for year-round layering.',
    price: 210,
    compare_price: null,
    category_id: 'cat-4',
    category: categories[3],
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Forest', hex: '#6a7c65' },
      { name: 'Charcoal', hex: '#5a5a5a' },
      { name: 'Sand', hex: '#c5b5a5' },
    ],
    stock_quantity: 8,
    is_featured: true,
    is_active: true,
    tags: ['outerwear', 'embroidered'],
    care_instructions: 'Dry clean only',
    material: 'Linen-Cotton Blend',
    created_at: '2026-02-08T00:00:00Z',
  },
  {
    id: 'p-8',
    name: 'Wool Blend Coat',
    slug: 'wool-blend-coat',
    description: 'A beautifully tailored mid-length coat in a warm wool blend. Clean lines, a single-breasted closure, and a slightly oversized fit for effortless layering.',
    price: 285,
    compare_price: 340,
    category_id: 'cat-4',
    category: categories[3],
    images: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&h=800&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Camel', hex: '#c5a882' },
      { name: 'Noir', hex: '#2c2c2c' },
    ],
    stock_quantity: 6,
    is_featured: false,
    is_active: true,
    tags: ['sale', 'wool', 'coat'],
    care_instructions: 'Professional dry clean',
    material: '70% Wool, 30% Polyester',
    created_at: '2026-01-05T00:00:00Z',
  },

  // ── BOTTOMS ──
  {
    id: 'p-9',
    name: 'Pleated Wide-Leg Trousers',
    slug: 'pleated-wide-leg-trousers',
    description: 'Elegant wide-leg trousers with a high waist and flowing pleats. The luxe drape and clean lines make these a sophisticated alternative to jeans.',
    price: 120,
    compare_price: null,
    category_id: 'cat-3',
    category: categories[2],
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Taupe', hex: '#b5a090' },
      { name: 'Ivory', hex: '#f5efe6' },
      { name: 'Sage', hex: '#8a9c85' },
    ],
    stock_quantity: 22,
    is_featured: true,
    is_active: true,
    tags: ['new', 'trousers'],
    care_instructions: 'Machine wash cold, hang to dry',
    material: 'Tencel-Linen Blend',
    created_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'p-10',
    name: 'Linen Palazzo Pants',
    slug: 'linen-palazzo-pants',
    description: 'Ultra-wide palazzo pants in lightweight linen with an elastic waist and side pockets. Breezy, relaxed, and effortlessly chic.',
    price: 95,
    compare_price: null,
    category_id: 'cat-3',
    category: categories[2],
    images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&h=800&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Natural', hex: '#d4c9bc' },
    ],
    stock_quantity: 16,
    is_featured: false,
    is_active: true,
    tags: ['linen', 'palazzo'],
    care_instructions: 'Machine wash cold, line dry',
    material: '100% Linen',
    created_at: '2026-01-22T00:00:00Z',
  },

  // ── ACCESSORIES ──
  {
    id: 'p-11',
    name: 'Woven Leather Tote',
    slug: 'woven-leather-tote',
    description: 'A hand-woven leather tote with a spacious interior and magnetic closure. Crafted from vegetable-tanned leather that develops a beautiful patina over time.',
    price: 178,
    compare_price: null,
    category_id: 'cat-5',
    category: categories[4],
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&h=800&fit=crop'],
    sizes: [],
    colors: [
      { name: 'Tan', hex: '#b5a090' },
      { name: 'Noir', hex: '#2c2c2c' },
    ],
    stock_quantity: 10,
    is_featured: false,
    is_active: true,
    tags: ['leather', 'bag', 'handcrafted'],
    care_instructions: 'Wipe with damp cloth, condition leather seasonally',
    material: 'Vegetable-Tanned Leather',
    created_at: '2026-02-03T00:00:00Z',
  },
  {
    id: 'p-12',
    name: 'Silk Hair Scarf',
    slug: 'silk-hair-scarf',
    description: 'A versatile pure silk scarf in an original botanical print. Wear it as a hair tie, neck scarf, or bag accessory for an instant touch of elegance.',
    price: 42,
    compare_price: null,
    category_id: 'cat-5',
    category: categories[4],
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&h=800&fit=crop'],
    sizes: [],
    colors: [
      { name: 'Sage Print', hex: '#7a8c75' },
      { name: 'Gold Print', hex: '#c9a84c' },
      { name: 'Rose Print', hex: '#d4a5a5' },
    ],
    stock_quantity: 30,
    is_featured: false,
    is_active: true,
    tags: ['silk', 'scarf', 'accessory'],
    care_instructions: 'Hand wash cold with silk detergent',
    material: '100% Mulberry Silk',
    created_at: '2026-01-25T00:00:00Z',
  },
];
